package main.kotlin.utils.listGames

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Paths

/**
 * Created by vbolinch on 03/01/2017.
 */
class ListGames {
    companion object {

        val columnNames = arrayOf("Load","ROM Game", "Game Name",  "ROM Type",  "Size (in bytes)")


        // val encryptedData = Files.readAllLines(Paths.get("/Users/vicboma/Downloads/draft-start-async-checkbutton-application-2/src/main/resources/gameList"), StandardCharsets.UTF_8)

        val data =
                arrayOf(
                arrayOf(false, "CADA.GB    ",    " ---  CADA  --- ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ACE_STRI.GB",    "ACE STRIKER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ADDAMSF.GB ",    "ADDAMS FAMILY   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ADDAMSF2.GB",    "ADDAMS FAMILY 2 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ADISLAND.GB",    "ADVENTURE ISLAND",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ADVENTU2.GB",    "ADVENTUREISLAND2",    "ROM+MBC1            ",262.144),
                arrayOf(false, "AEROSTAR.GB",    "AEROSTAR        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "AFTERBUR.GB",    "AFTER BURST     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ALADDIN.GB ",    "ALADDIN         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ALFREDCH.GB",    "ALFRED CHICKEN  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ALIENS3.GB ",    "ALIEN           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ALIOLYM.GB ",    "ALIEN OLYMPICS  ",    "ROM+MBC1            ",131.07 ),
                arrayOf(false, "ALIENVSP.GB",    "ALIEN V PREDATOR",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ALLEYWAY.GB",    "ALLEY WAY       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "ALLSTAR.GB ",    "ALLSTARCHALLENGE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ALLSTAR2.GB",    "ALSTARCHALLENGE2",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ALLSTR2J.GB",    "ALSTARCHALLENGE2",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ALTSPACE.GB",    "ALTERED SPACE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ALTSPACJ.GB",    "ALTERED SPACE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "AMAZINGT.GB",    "AMAZING-TATER   ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "AMIDA.GB   ",    "AMIDA           ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "ANIMANIA.GB",    "ANIMANIACS      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ANOTHERB.GB",    "ANOTHER BIBLE   ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "ARETHA.GB  ",    "ARETHA          ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "ARETHA3.GB ",    "ARETHA3         ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "ASMIK2.GB  ",    "ASMIK2          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ASTERIX.GB ",    "ASTERIX         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ASTEROID.GB",    "ASTEROIDS       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "ASTEROIM.GB",    "ASTEROIDS/MISCMD",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ASTRORAB.GB",    "ASTRO RABBY     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ATOMIC_P.GB",    "ATOMIC PUNK     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "AVENGING.GB",    "AVENGING SPIRIT ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "AYAKASI.GB ",    "AYAKASI NO SIRO ",    "ROM+MBC2+BATTERY    ", 65.536 ),
                arrayOf(false, "BCKID2.GB  ",    "B.C.KID2        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BALLOON.GB ",    "BALLOON KID     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BANISH.GB  ",    "BANISHING RACER ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BARBIE.GB  ",    "BARBIE GAME GIRL",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BASEBALK.GB",    "BASE BALL KIDS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BASEBALL.GB",    "BASEBALL        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BASES_LO.GB",    "BASES LOADED GB ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATMAN.GB  ",    "BATMAN          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATMANAS.GB",    "BATMAN ANIMATED ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATMAN4E.GB",    "BATMAN FOREVER  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BATMANRJ.GB",    "BATMAN ROJ      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATLBULL.GB",    "BATTLE BULL     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATLCRUS.GB",    "BATTLE CRUSHER  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BATLOFKD.GB",    "BATTLE OFKINGDOM",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATLPP.GB  ",    "BATTLE PINGPONG ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GBATSHIP.GB",    "BATTLE SHIP     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BATTLESH.GB",    "BATTLE SHIP     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GBATSHIP.GB",    "BATTLE SHIP     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BATTLESH.GB",    "BATTLE SHIP     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BATLCITY.GB",    "BATTLECITY      ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BATLTOAD.GB",    "BATTLETOADS     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "B-ZEOTH.GB ",    "BATTLEUNIT ZEOTH",    "ROM+MBC1            ",131.072),
                arrayOf(false, "VOLLEYBM.GB",    "BEACH,VOLLEYBALL",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BEACHVOL.GB",    "BEACH_VOLLEY    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BEETHOV2.GB",    "BEETHOVEN       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BEETLEJU.GB",    "BEETLEJUICE     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BEST_BES.GB",    "BEST OF THE BEST",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BIKKURI.GB ",    "BIKKURI NEKKETU ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BILL&TED.GB",    "BILL AND TED    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BIONICBA.GB",    "BIONIC BATTLER  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BIONICC.GB ",    "BIONIC-COMMANDO ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BIONICJ.GB ",    "BIONIC-COMMANDO ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BISHOJYO.GB",    "BISHOJYOSENSI SE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BLADES.GB  ",    "BLADES OF STEEL ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BM_BOY.GB  ",    "BLASTER MASTER B",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BLODIA.GB  ",    "BLODIA          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BLUESBR1.GB",    "BLUES BROTHERS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BOJACKSO.GB",    "BO JACKSON      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BOKUDRAC.GB",    "BOKU DRACURA KUN",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BOMBJACK.GB",    "BOMB JACK       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BOMBER_B.GB",    "BOMBER BOY      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BOMBER_K.GB",    "BOMBER KING S2  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BOMBER_N.GB",    "BOMBER MAN GB   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BOMBER_M.GB",    "BOMBERMAN GB    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BONKSADV.GB",    "BONK'S ADVENTURE",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BOOBYBOY.GB",    "BOOBY BOYS      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "BOUKENJI.GB",    "BOUKENJIMA2     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BOULDERD.GB",    "BOULDER DASH    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BOULDERJ.GB",    "BOULDER DASH    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BOXING.GB  ",    "BOXING          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BOXXLE.GB  ",    "BOXXLE          ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BOXXLE2.GB ",    "BOXXLE2         ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BOY&BLOB.GB",    "BOY AND BLOB GB1",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BOYBLOB.GB ",    "BOY AND BLOB GB2",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BOYBLOB.GB ",    "BOY AND BLOB GB2",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BRAINB.GB  ",    "BRAINBENDER     ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BREAKTHR.GB",    "BREAKTHRU!      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATLTOA2.GB",    "BT2RAGNAROKWORLD",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BUBBLE90.GB",    "BUBBLE BOBBLE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BUBBLE91.GB",    "BUBBLE BOBBLE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BUBBLEG.GB ",    "BUBBLE GHOST    ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BUBGHOST.GB",    "BUBBLE GHOST    ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "BUBBLE2.GB ",    "BUBBLEBOBBLE2   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BUBBLEJR.GB",    "BUBBLEBOBBLEJR  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BUBSY2.GB  ",    "BUBSY II        ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "BUGSBUNN.GB",    "BUGS BUNNY      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BUGSCRAZ.GB",    "BUGSCRAZYCASTLE2",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BURAI.GB   ",    "BURAI FIGHTER DE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BURAIJ.GB  ",    "BURAI FIGHTER DX",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BURGER_T.GB",    "BURGER TIME     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BURNPAPR.GB",    "BURNING PAPER   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BATLZONE.GB",    "BZONE SBREAKOUT ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "CADILLAC.GB",    "CADILLAC2       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "CAESARSJ.GB",    "CAESARS PALACE  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CAESARSP.GB",    "CAESARS PALACE  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "QUIZ.GB    ",    "CAPCOM QUIZ     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "CAPTAINT.GB",    "CAPTAIN TUBASA J",    "ROM+MBC1            ",524.288),
                arrayOf(false, "CARDGAME.GB",    "CARD GAME       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "CASINOFP.GB",    "CASINO FUNPAK   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CASTELIA.GB",    "CASTELIAN       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "CASTLE91.GB",    "CASTLEVANIA ADVE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "CASTLE89.GB",    "CASTLEVANIA ADVE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "CASTLEV2.GB",    "CASTLEVANIA2 BEL",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CAVE_NOI.GB",    "CAVE NOIRE      ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "CENTIPED.GB",    "CENTIPEDE       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "CHACHAMA.GB",    "CHACHAMARUPANIC ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "CHASEHQ.GB ",    "CHASE HQ        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CHASE_HQ.GB",    "CHASE HQ        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CHIBIMAR.GB",    "CHIBIMARUKO     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "CHIKI.GB   ",    "CHIKI RACE GB   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "CHOPLIFT.GB",    "CHOPLIFTER 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CHOPLIF2.GB",    "CHOPLIFTER 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CHOPLIF3.GB",    "CHOPLIFTER III  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BASEBALR.GB",    "CLEMENS BASEBALL",    "ROM+MBC1            ",262.144),
                arrayOf(false, "CLIFFHAN.GB",    "CLIFFHANGER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CONTRA.GB  ",    "CONTRA          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CONTRA_S.GB",    "CONTRA SPIRITS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "COOLSPOT.GB",    "COOL SPOT       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "COOLWORL.GB",    "COOL WORLD      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "COSMOTNK.GB",    "COSMO TANK      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CRASHDUM.GB",    "CRASH DUMMIES   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CRYSTALQ.GB",    "CRYSTAL QUEST   ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "CUTTHROA.GB",    "CUTTHROAT ISLAND",    "ROM+MBC1            ",262.144),
                arrayOf(false, "CYBERFOR.GB",    "CYBER FORMULA   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CYRAID.GB  ",    "CYRAID          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DAEDOPUS.GB",    "DAEDALIAN OPUS  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "DAFFY.GB   ",    "DAFFY DUCK      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DAFFY2.GB  ",    "DAFFY DUCK      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DAISENRY.GB",    "DAISENRYAKU HIRO",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "DARKWING.GB",    "DARK WING DUCK  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DARKMAN.GB ",    "DARKMAN         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DARUMAN.GB ",    "DARUMAN BUSTERS ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DAYSOFTH.GB",    "DAYS OF THUNDER ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DEADHEAJ.GB",    "DEADHEATSCRAMBLE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DEADHEAT.GB",    "DEADHEATSCRAMBLE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DEFENDER.GB",    "DEFENDER/JOUST  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DENNIS.GB  ",    "DENNIS          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DESERT_S.GB",    "DESERT STRIKE   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DEXTERTY.GB",    "DEXTERITY       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DICKTRAC.GB",    "DICK TRACY      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DIGDUG.GB  ",    "DIG DUG         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRAGONSL.GB",    "DLAIR LEGEND UK0",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DLAIRLGD.GB",    "DLAIR THE LEGEND",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DMGFOOTB.GB",    "DMG FOOTBALL    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BOOMERSA.GB",    "DMG-ASE         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "BOOMERSJ.GB",    "DMG-ASJ         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DMG-KMJ.GB ",    "DMG-KMJ         ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SNOWBROS.GB",    "DMG-SJJ         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DMG-UQJ.GB ",    "DMG-UQJ         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DODGEBAL.GB",    "DODGE BALL      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DODGEBOY.GB",    "DODGE BOY       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DODGEDAN.GB",    "DODGEDANPEI     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DKONG.GB   ",    "DONKEY KONG     ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "DKLAND2.GB ",    "DONKEYKONGLAND 2",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "DKLAND3.GB ",    "DONKEYKONGLAND 3",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "DKONGL95.GB",    "DONKEYKONGLAND95",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "DORAEMON.GB",    "DORAEMON        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DORAEMO1.GB",    "DORAEMON        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DORAEMO2.GB",    "DORAEMON2       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CASTLEJ.GB ",    "DORAKYURADENSETU",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DORASURE.GB",    "DORASUREGAIDEN  ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "DOUBLED.GB ",    "DOUBLE DRAGON   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DOUBLED2.GB",    "DOUBLE DRAGON 2 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DOUBLED3.GB",    "DOUBLE DRAGON 3 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DOUBLEDR.GB",    "DOUBLE DRIBBLE  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DOUBLEYA.GB",    "DOUBLEYAKUMAN2  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRFRANK.GB ",    "DR FRANKEN      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRFRANJ.GB ",    "DR FRANKEN      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRFRANK2.GB",    "DR FRANKEN 2    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DRMARIO.GB ",    "DR.MARIO        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "DRACULA.GB ",    "DRACULA         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CASTLEJ2.GB",    "DRACURA2        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRAGONS1.GB",    "DRAGON SLAYER 1 ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "DRGHEART.GB",    "DRAGONHEART     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DRAGONH.GB ",    "DRAGONHEART     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "DRAGONSR.GB",    "DRAGONS LAIR    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRAGONTA.GB",    "DRAGONTAILBIT2  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DROPZONE.GB",    "DROPZONE        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "DUCKTJ.GB  ",    "DUCK TALES      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DUCKT.GB   ",    "DUCK TALES      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "DUCKT2J.GB ",    "DUCK TALES 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DUCKT2.GB  ",    "DUCK TALES 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DUNGEONL.GB",    "DUNGEONLAND     ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "DYNABLAS.GB",    "DYNABLASTER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "EARTHJIM.GB",    "EARTHWORM JIM   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ELEVATOJ.GB",    "ELEVATOR ACTION ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ELEVATOR.GB",    "ELEVATOR ACTION ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SOCCERE.GB ",    "ELITE SOCCER    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "STARWARE.GB",    "EMPIRE STRIKES  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ESPARKS.GB ",    "ESPARKS         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "F1HEROG.GB ",    "F-1 HEROGB      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "F1HERO.GB  ",    "F-1HERO GB92    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "F1_BOY.GB  ",    "F1 BOY          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "F1SPIRIT.GB",    "F1 SPIRIT       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "F1_SD.GB   ",    "F1 SUPER DRIVING",    "ROM+MBC1            ",262.144),
                arrayOf(false, "F15_STRI.GB",    "F15 STRIKE EAGLE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "F1_RACE.GB ",    "F1RACE          ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "FACEBALL.GB",    "FACEBALL 2000   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FAMILYJ.GB ",    "FAMILYJOCKEY    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FASTESTL.GB",    "FASTEST LAP     ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "FELIX.GB   ",    "FELIX THE CAT   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FERRARI.GB ",    "FERRARI         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SOCCERF.GB ",    "FIFA SOCCER     ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "FIFASOCC.GB",    "FIFA SOCCER 96  ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "FIGHBIRD.GB",    "FIGHBIRD  GB    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FIGHTING.GB",    "FIGHTING SOCCER ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "FINALREV.GB",    "FINAL REVERSE   ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "FIRE_FIG.GB",    "FIRE FIGHTER    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FISHDUDE.GB",    "FISH DUDE       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "FLAPPY.GB  ",    "FLAPPY SPECIAL  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "FLINTKRT.GB",    "FLINTSTONES     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FLIPULL.GB ",    "FLIPULL         ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "FIGHTSIM.GB",    "FLYING WARRIORS ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FOOTBALL.GB",    "FOOTBALL INT'L  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FOREMAN.GB ",    "FOREMAN FOR REAL",    "ROM+MBC1            ",262.144),
                arrayOf(false, "FORTZONE.GB",    "FORTIFIED ZONE  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FORTZON2.GB",    "FORTIFIED ZONE2 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "THOMASBB.GB",    "FRANK THOMAS BB ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "FUNNY_FI.GB",    "FUNNY FIELD     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "FUNPACK.GB ",    "FUNPAK 4IN1     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FUNPACK2.GB",    "FUNPAK 4IN1 - V2",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FUSHIGIN.GB",    "FUSHIGINA BULOBI",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "G&W.GB     ",    "G&W GALLERY     ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "GALAGAX.GB ",    "GALAGA&GALAXIAN ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GAME&WAT.GB",    "GAME&WATCH      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GAMERA.GB  ",    "GAMERA DAIKAIJUU",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GANBAREG.GB",    "GANBARE GOEMON  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GARFIELD.GB",    "GARFIELD        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GARGOYLE.GB",    "GARGOYLE'S      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GAUNTLET.GB",    "GAUNTLET II     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TAMA&FRI.GB",    "GB 3TAMA        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BASKET.GB  ",    "GB BASKETBALL   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BEACHV91.GB",    "GB BEACHVOLLEY  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "DRAGONBZ.GB",    "GB DBZ GOKOU    ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "DRUAGA.GB  ",    "GB DRUAGA 1     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GARMS.GB   ",    "GB GARMS 1      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GENJIN.GB  ",    "GB GENJIN       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GENJINLD.GB",    "GB GENJIN LAND  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBGODZ.GB  ",    "GB GODZILLA     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "IRONLEAG.GB",    "GB IRON LEAGUER1",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBJIDAIG.GB",    "GB JIDAIGEKI    ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "KINNIKUM.GB",    "GB KINNIKUMAN DM",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBKUREY4.GB",    "GB KUREYON SHIN ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KUREYON.GB ",    "GB KUREYON SHIN4",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBLACRO1.GB",    "GB LACROANHERO 1",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "GBMASKR.GB ",    "GB MASKRIDER SD ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MUSASHIR.GB",    "GB MUSASHIROAD 1",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBMUSASH.GB",    "GB MUSASHIROAD 1",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GUNDAMB.GB ",    "GB NEW SD GUNDAM",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBOTOKO1.GB",    "GB OTOKOJYUKU 1 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBOTOKOJ.GB",    "GB OTOKOJYUKU 1 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "OTOKOJYU.GB",    "GB OTOKOJYUKU 1 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MIGHTMPM.GB",    "GB POWER MOVIE  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SAILORM.GB ",    "GB SAILORMOON R ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SAILOR.GB  ",    "GB SAILORMOON R ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SLAMDUNK.GB",    "GB SLAM DUNK    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SLAMDNK2.GB",    "GB SLAM DUNK 2  ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "SUPERBIK.GB",    "GB SUPERBIKKURI1",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBTAACHI.GB",    "GB TAACHIYAN    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TAMAJ.GB   ",    "GB TAMAGOTCH 1  ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "TAMA.GB    ",    "GB TAMAGOTCHI   ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "GBTARU1.GB ",    "GB TARURU-TO 1  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBTARU2.GB ",    "GB TARURU-TO 2  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TEKKAMAN.GB",    "GB TEKKAMANBLADE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBULTRA1.GB",    "GB ULTRAMANCLUB1",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "UNDOUKAI.GB",    "GB UNDOUKAI     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GENJIN2.GB ",    "GBGENJIN2       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBWARS.GB  ",    "GBWARS          ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "GEMGEM.GB  ",    "GEMGEM          ",    "ROM+MBC1+RAM+BATTERY", 65.536 ),
                arrayOf(false, "STGENRAT.GB",    "GENERATIONS     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GENSAJ.GB  ",    "GENSAN          ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GENSAN.GB  ",    "GENSAN          ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GENSAN2.GB ",    "GENSAN2         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "FOREMANK.GB",    "GEORGE F. BOXING",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GHOSTBU2.GB",    "GHOSTBUSTERS 2  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GHOSTBUS.GB",    "GHOSTBUSTERS II ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GINGA.GB   ",    "GINGA           ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GOGOTANK.GB",    "GO GO TANK      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GOAL.GB    ",    "GOAL!           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GODMEDIC.GB",    "GOD MEDICINE    ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "GODZILLA.GB",    "GODZILLA        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GOLF.GB    ",    "GOLF            ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "GOLFCLAS.GB",    "GOLF CLASSIC    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MR_CHIN.GB ",    "GOURMET PARADISE",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GRADIUS.GB ",    "GRADIUS         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GREMLIN2.GB",    "GREMLINS 2      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HARIMANA.GB",    "HARIMANADA      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HATRIS.GB  ",    "HATRIS          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "HEAD_ON.GB ",    "HEAD ON         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "HEIANKYJ.GB",    "HEIANKYO ALIEN  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "HEIANKYO.GB",    "HEIANKYO ALIEN  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "HERCULES.GB",    "HERCULES EIKOU  ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "HIGH_STA.GB",    "HIGH STAKES     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HIRYUGAI.GB",    "HIRYU GAIDEN    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HOMEALON.GB",    "HOME ALONE      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HOMEALO2.GB",    "HOME ALONE2     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HONGKONG.GB",    "HONG KONG       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "HOOK.GB    ",    "HOOK            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HOOK2.GB   ",    "HOOK            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HOSHINOK.GB",    "HOSHINOKA-BI    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "HUDSON.GB  ",    "HUDSON HAWK     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HUDSONJ.GB ",    "HUDSON HAWK     ",    "ROM+MBC1            ", 77.828 ),
                arrayOf(false, "HUGO.GB    ",    "HUGO            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HYPRBLAC.GB",    "HYPER BLACKBASS ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "HYPRDUNK.GB",    "HYPER DUNK      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HYPRLODE.GB",    "HYPERLODERUNNER ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "IKARINOY.GB",    "IKARI NO YOUSAI ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "IN_YOUR.GB ",    "IN YOUR FACE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "INDIANAJ.GB",    "INDIANA JONES   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "INDIANA3.GB",    "INDIANA JONES 3 ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "IREMFIGH.GB",    "IREM FIGHTER    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ISHIDOJ.GB ",    "ISHIDO JPN VER. ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "ISHIDO.GB  ",    "ISHIDO USA VER. ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SIMPSONI.GB",    "ITCHY & SCRATCHY",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TENNISJC.GB",    "J CONNOR TENNIS ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "JCUPSOCC.GB",    "J.CUP SOCCER    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERJP.GB ",    "JAMES POND      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "JANKENMA.GB",    "JANKENMAN       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "JANSHIRO.GB",    "JANSHIRO        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "JANTAKUB.GB",    "JANTAKUBOY      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "JEEPJAMB.GB",    "JEEP JAMBOREE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "JELLYBOY.GB",    "JELLY BOY       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JEOPARDY.GB",    "JEOPARDY        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "JINSEI.GB  ",    "JINSEI          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBJOEMAC.GB",    "JOE AND MAC     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JOE&MAC.GB ",    "JOE AND MAC     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBJOEMAC.GB",    "JOE AND MAC     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JORDANON.GB",    "JORDAN ONEONONE ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "JORDAN_V.GB",    "JORDAN VS BIRD  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "JUDGEDRE.GB",    "JUDGE DREDD     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JUNGLE.GB  ",    "JUNGLE BOOK     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "JUNGLEST.GB",    "JUNGLE STRIKE   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JUNGLEWA.GB",    "JUNGLE WARS     ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "JPARK.GB   ",    "JURASSIC PARK   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JPARK2.GB  ",    "JURASSIC PARK II",    "ROM+MBC1            ",262.144),
                arrayOf(false, "KAERUNO.GB ",    "KAERUNOTAMENI   ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "KAGUYAHI.GB",    "KAGUYAHIME      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KATTOBIR.GB",    "KATTOBI ROAD    ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "KESAMARU.GB",    "KESAMARU        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "KIDICARU.GB",    "KID ICARUS      ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "KIDNIKI.GB ",    "KID NIKI        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "KILLERTO.GB",    "KILLER TOMATOES ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KILLINST.GB",    "KILLERINSTINCT95",    "ROM+MBC1            ",524.288),
                arrayOf(false, "KINGDOMC.GB",    "KINGDOM CRUSADE ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KINGOZOO.GB",    "KINGOFTHEZOO    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "KINTAROA.GB",    "KINTARO ACG     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "KIRBYBB.GB ",    "KIRBY BLOCKBALL ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "KIRBYDL.GB ",    "KIRBY DREAM LAND",    "ROM+MBC1            ",262.144),
                arrayOf(false, "KIRBYPIJ.GB",    "KIRBY'S PINBALL ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "KIRBYPIN.GB",    "KIRBY'S PINBALL ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "KIRBYDL2.GB",    "KIRBY2          ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "KITCHENP.GB",    "KITCHIN PANIC   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KITERETU.GB",    "KITERETU ZYURAKI",    "ROM+MBC1            ",262.144),
                arrayOf(false, "KLAX.GB    ",    "KLAX            ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "KNIGHTQ.GB ",    "KNIGHT QUEST    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KOIWAKAK.GB",    "KOI WA KAKEHIKI ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "GOLFK.GB   ",    "KONAMI GOLF     ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "SPORTS.GB  ",    "KONAMIC SPORTS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KORODICE.GB",    "KORODICE        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SIMPSONK.GB",    "KRUSTY          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KUNIO.GB   ",    "KUNIO           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KWIRK.GB   ",    "KWIRK           ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "NEBULOUS.GB",    "KYORCHANLANDHIRO",    "ROM Only            ", 32.768 ),
                arrayOf(false, "LAMBORGH.GB",    "LAMBORGHINI     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FRENCH.GB  ",    "LANG TRNSLTR FRN",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPANISH.GB ",    "LANG TRNSLTR SPN",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LASTACTI.GB",    "LAST ACTION HERO",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LASTBIB.GB ",    "LAST BIBLE      ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "LASTBIB2.GB",    "LAST BIBLE2     ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "LAWNMOWR.GB",    "LAWNMOWER MAN   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LAZLOSL.GB ",    "LAZLOS LEAP     ",    "ROM+MBC2+BATTERY    ", 32.768 ),
                arrayOf(false, "LEGEND.GB  ",    "LEGEND          ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "LEGENDOZ.GB",    "LEGEND OF ZERD  ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "LEMMINGS.GB",    "LEMMINGS        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LEMMING2.GB",    "LEMMINGS 2      ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "LETHALWE.GB",    "LETHAL WEAPON   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LITTLEM.GB ",    "LITTLE MASTER   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "LITTLEM2.GB",    "LITTLE MASTER 2 ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "LITTLE_M.GB",    "LITTLE MERMAID  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LOCKCHAS.GB",    "LOCK'N CHASE    ",    "ROM+MBC1            ",65.536 ),
                arrayOf(false, "LOLO.GB    ",    "LOLO            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LOONEY.GB  ",    "LOONEY TUNES    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LOOPZ.GB   ",    "LOOPZ           ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "LUCKYMON.GB",    "LUCKY MONKEY    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "LUCLE.GB   ",    "LUCLE           ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "LUNALAND.GB",    "LUNA LANDER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MADDEN95.GB",    "MADDEN 95       ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "MADDEN96.GB",    "MADDEN 96       ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "MAGNETIC.GB",    "MAGNETIC SOCCER ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MAHOUJIN.GB",    "MAHOUJINGURUGURU",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MAKAIMUR.GB",    "MAKAIMURAGAIDEN ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MANSELL.GB ",    "MANSELL         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MARBLE_M.GB",    "MARBLE MADNESS  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MARIO&YO.GB",    "MARIO & YOSHI   ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MARIOSPI.GB",    "MARIO'S PICROSS ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "SUPERML2.GB",    "MARIOLAND2      ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "MARUS_M.GB ",    "MARU'S MISSION  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MASTERKA.GB",    "MASTER KARATEKA ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "MCDONALD.GB",    "MCDONALDLAND    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MEGAMAN2.GB",    "MEGA MAN 2      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBMEGMN2.GB",    "MEGA MAN 2      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBMEGMN2.GB",    "MEGA MAN 2      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MEGALIT.GB ",    "MEGALIT         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MEGAMAN.GB ",    "MEGAMAN         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBMEGMN3.GB",    "MEGAMAN3        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBMEGMN3.GB",    "MEGAMAN3        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MEGAMAN3.GB",    "MEGAMAN3        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MEGAMAN4.GB",    "MEGAMAN4        ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "M-FORCE.GB ",    "MERCENARY FORCE ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "METALJAC.GB",    "METALJACK       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "METROID2.GB",    "METROID2        ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "MICKEY4.GB ",    "MICKEY 4        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MICKEY5.GB ",    "MICKEY 5        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBMICKYV.GB",    "MICKEY MOUSE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBMICKYV.GB",    "MICKEY MOUSE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MICKEY.GB  ",    "MICKEY MOUSE    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MICKEY2.GB ",    "MICKEY MOUSE 2  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MICKCHAS.GB",    "MICKEYS CHASE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MICRMACH.GB",    "MICRO MACHINES  ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "MICROMA2.GB",    "MICRO MACHINES 2",    "ROM+MBC1            ",524.288),
                arrayOf(false, "MIGRAINA.GB",    "MIGRAIN ACCLAIM ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "MIKENEKO.GB",    "MIKENEKO HOLMES ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MILLCENT.GB",    "MILLI/CENTI/PEDE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MILON.GB   ",    "MILON CASTLE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MINR2049.GB",    "MINER 2049ER    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MINE.GB    ",    "MINESWEEPER     ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "MINIPUTT.GB",    "MINI PUTT       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MISSLE.GB  ",    "MISSILE COMMAND ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "MICKEYUC.GB",    "MM ULT CHALLENGE",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MOGURADE.GB",    "MOGURA DE PON!  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "MOLEMANI.GB",    "MOGURANYA       ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "MOMOTAR1.GB",    "MOMOTARO DENGEKI",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MOMOTAR2.GB",    "MOMOTARODENGEKI2",    "ROM+MBC1            ",524.288),
                arrayOf(false, "MOMOTETU.GB",    "MOMOTETU        ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "MONOPOLY.GB",    "MONOPOLY        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MONOPJ.GB  ",    "MONOPOLY        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MONSTERK.GB",    "MONSTER MAKER J ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "MONSTERL.GB",    "MONSTER MAKER J2",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "MONSTERM.GB",    "MONSTER MAX     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MONSTERT.GB",    "MONSTERTRUCK    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MK.GB      ",    "MORTAL KOMBAT   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MK3.GB     ",    "MORTAL KOMBAT 3 ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "MK2.GB     ",    "MORTAL KOMBAT II",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MOTOCROS.GB",    "MOTOCROSSMANIACS",    "ROM Only            ", 32.768 ),
                arrayOf(false, "MOUSETRA.GB",    "MOUSE TRAP HOTEL",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MR_NUTZ.GB ",    "MR NUTZ         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "MRDO.GB    ",    "MR.DO!          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MSPACMAN.GB",    "MS.PAC-MAN      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MUHAMMAD.GB",    "MUHAMMAD ALI    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MYSTERIU.GB",    "MYSTERIUM       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "MYSTICG.GB ",    "MYSTIC QUEST    ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "MYSTIC.GB  ",    "MYSTIC QUEST    ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "MYSTICF.GB ",    "MYSTIC QUEST    ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "NAILNSCA.GB",    "NAIL N SCALE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NAMCOCLA.GB",    "NAMCOCLASSIC    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BILLELLI.GB",    "NASCARFASTTRACKS",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NAVYBLUE.GB",    "NAVY BLUE       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "NAVYBLUF.GB",    "NAVY BLUE 90    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NAVYSEAL.GB",    "NAVY SEALS      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NBAJAM.GB  ",    "NBA JAM         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "NBAJAMTE.GB",    "NBA JAM TE      ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "NEKOJARA.GB",    "NEKOJARA        ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "NEMESIS.GB ",    "NEMESIS         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NEMESIS2.GB",    "NEMESIS 2       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "KOF95.GB   ",    "NETTOU KOF 95   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "SAMURAIN.GB",    "NETTOU SAMURAI  ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "NETTOUT.GB ",    "NETTOU TOSHINDEN",    "ROM+MBC1            ",524.288),
                arrayOf(false, "WORLDH2J.GB",    "NETTOU WH2JET   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "NETWH2JT.GB",    "NETTOU WH2JET   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "NETTOUG2.GB",    "NETTOUGAROU2    ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "CHESSM2.GB ",    "NEW CHESSMASTER ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "NFL_FB.GB  ",    "NFL FOOTBALL    ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "NFL96.GB   ",    "NFL QB CLUB 96  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "NHL95.GB   ",    "NHL HOCKEY 95   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "NINJABOY.GB",    "NINJA BOY       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "NINJABO2.GB",    "NINJA BOY 2     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "NGAIDEN.GB ",    "NINJA GAIDEN    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NINJA_G.GB ",    "NINJA GAIDEN    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NINJARYU.GB",    "NINJA RYUKENDEN ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NINJASPI.GB",    "NINJA SPIRIT    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "NINJA_T.GB ",    "NINJATARO       ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "NOBUNAGJ.GB",    "NOBUNAGA        ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "NOBUNAGA.GB",    "NOBUNAGA        ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "NORTHSTA.GB",    "NORTH STAR      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "OBELIX.GB  ",    "OBELIX          ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "OIRAJAJA.GB",    "OIRA JAJAMARU   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "OLYMPICG.GB",    "OLYMPIC GAMES   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "OLYMPUS.GB ",    "OLYMPUS         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ON_TILES.GB",    "ON THE TILES    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ONI.GB     ",    "ONI             ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "ONI5.GB    ",    "ONI 5           ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "ONIPACH.GB ",    "ONI-PACHINKOTEN ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "OPERAC.GB  ",    "OPERATION C     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "OTHELLO.GB ",    "OTHELLO         ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "OUTBURST.GB",    "OUT BURST       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "OUTOFGAS.GB",    "OUT OF GAS      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PACNTIME.GB",    "PAC-IN-TIME     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PACMAN.GB  ",    "PAC-MAN         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PAC-MAN.GB ",    "PAC-MAN         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PACMANJ.GB ",    "PAC-MAN         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PACPANIC.GB",    "PAC-PANIC       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PACHINKO.GB",    "PACHINKO TIME   ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PAINTERM.GB",    "PAINTERMOMOPIE  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PALAMEDE.GB",    "PALAMEDES       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "PANG.GB    ",    "PANG            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PAPERBOY.GB",    "PAPERBOY        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PAPUWAKU.GB",    "PAPUWAKUNN      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PARASOL.GB ",    "PARASOL STARS   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PARASORU.GB",    "PARASORU HEMBEI ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PARODIUS.GB",    "PARODIUS        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PARODIUJ.GB",    "PARODIUS DA!    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PEETAN.GB  ",    "PEETAN          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PENGUINB.GB",    "PENGUIN BOY     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PENGUINL.GB",    "PENGUIN LAND    ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "PENGUINW.GB",    "PENGUIN WARS    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PENGUINK.GB",    "PENGUINKUNWARSVS",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PENTADRA.GB",    "PENTADRAGON     ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "ORGANIZE.GB",    "PERSONAL ORGANIZ",    "ROM+MBC1+RAM+BATTERY", 65.536 ),
                arrayOf(false, "PGAEUROP.GB",    "PGA EURO TOUR   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "PGATOU96.GB",    "PGA TOUR 96     ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "PHANTASM.GB",    "PHANTASM        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBPINBLL.GB",    "PINBALL         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GBPINBLL.GB",    "PINBALL         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PINBALL.GB ",    "PINBALL         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PINBALLJ.GB",    "PINBALL         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PINBALLD.GB",    "PINBALL DELUXE  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PINBALLE.GB",    "PINBALL DREAMS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PINBALLF.GB",    "PINBALL FANTASIE",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PINMANIA.GB",    "PINBALL MANIA   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PINBALLP.GB",    "PINBALL PARTY   ",    "ROM+MBC1            ",65.536 ),
                arrayOf(false, "PIPEDREA.GB",    "PIPE DREAM      ",    "ROM Only            ",32.768 ),
                arrayOf(false, "PITFIGHT.GB",    "PIT FIGHTER     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PITMAN.GB  ",    "PITMAN          ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "POCAHONT.GB",    "POCAHONTAS      ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "POCKBATL.GB",    "POCKET BATTLE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POCKSTAD.GB",    "POCKET STADIUM  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "POKONYAN.GB",    "POKONYAN!       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "POPUP.GB   ",    "POP UP          ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "POPEYE.GB  ",    "POPEYE          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POPEYE2.GB ",    "POPEYE 2        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POPEY2.GB  ",    "POPEYE 2        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POPULOUS.GB",    "POPULOUS        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POWERM.GB  ",    "POWER MISSION   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POWERMIS.GB",    "POWER MISSION   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "POWERRAC.GB",    "POWER RACER     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MIGHTMPR.GB",    "POWER RANGERS   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PREHISTO.GB",    "PREHISTORIK MAN ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PRIMAL_R.GB",    "PRIMAL RAGE     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PRINCE.GB  ",    "PRINCE OF PERSIA",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PRINCEJ.GB ",    "PRINCE OF PERSIA",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PRIPRI.GB  ",    "PRIPRI          ",    "ROM+MBC1            ",65.536 ),
                arrayOf(false, "PROSOCCE.GB",    "PRO SOCCER      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PROBO.GB   ",    "PROBOTECTOR     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PROBO2.GB  ",    "PROBOTECTOR 2   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PROWRES.GB ",    "PROWRES         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HALWREST.GB",    "PROWRES         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "PUROSTAD.GB",    "PURO STADIUM '91",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "PUYOPUYO.GB",    "PUYOPUYO        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PUZZLBOY.GB",    "PUZZLE BOY      ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "PUZZLEB2.GB",    "PUZZLE BOY2     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PUZZLROA.GB",    "PUZZLE ROAD     ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "PUZZNIC.GB ",    "PUZZNIC         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "PYRAMIDS.GB",    "PYRAMIDS OF RA  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "QBERT2J.GB ",    "Q*BERT II       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "QBERT2.GB  ",    "Q*BERT II       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "QBILLION.GB",    "QBILLION        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "QIX.GB     ",    "QIX             ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "QUARTHJ.GB ",    "QUARTH          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "QUARTH.GB  ",    "QUARTH          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RACEDAYS.GB",    "RACE DAYS       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "RACE_DRI.GB",    "RACE DRIVIN'    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RACINGDA.GB",    "RACING DAMASHII ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RADARMJ.GB ",    "RADARMISSION    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RADARM.GB  ",    "RADARMISSION    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RAGINGFI.GB",    "RAGING FIGHTER  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "RAIJINOU.GB",    "RAIJINOU        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RAMPART.GB ",    "RAMPART_GB      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RANMA.GB   ",    "RANMA 1/2       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RANMA2.GB  ",    "RANMA1/2 PART2  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "RANMAK.GB  ",    "RANMA1/2KAKUGEKI",    "ROM+MBC1            ",262.144),
                arrayOf(false, "RAYTHUND.GB",    "RAY THUNDER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "REALGHOS.GB",    "REAL GHOSTBUSTER",    "ROM+MBC1            ",131.072),
                arrayOf(false, "REDARREM.GB",    "RED ARREMER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RED_OCT.GB ",    "RED OCTOBER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RED_OCTJ.GB",    "RED OCTOBER     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RIDDICK.GB ",    "RIDDICK BOWE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RINGRAGE.GB",    "RING RAGE       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ROADRASH.GB",    "ROAD RASH       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ROBINHOO.GB",    "ROBIN HOOD      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ROBOCOPJ.GB",    "ROBOCOP         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ROBOCOP.GB ",    "ROBOCOP         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ROBOCOP2.GB",    "ROBOCOP2        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ROCKNMON.GB",    "ROCK'N! MONSTER!",    "ROM+MBC1            ",524.288),
                arrayOf(false, "ROCKMAN.GB ",    "ROCKMAN WORLD   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ROCKMAN2.GB",    "ROCKMAN WORLD2  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ROCKMAN3.GB",    "ROCKMANWORLD3   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ROCKMAN4.GB",    "ROCKMANWORLD4   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "ROCKMAN5.GB",    "ROCKMANWORLD5   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "ROCKY&BU.GB",    "ROCKY BULLWINKLE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RODLAND.GB ",    "RODLAND         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RODLANDJ.GB",    "RODLAND         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ROGER_R.GB ",    "ROGER RABBIT    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ROLANSC2.GB",    "ROLAN'S CURSE 2 ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "ROLANSC.GB ",    "ROLANS CURSE    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RTYPE.GB   ",    "RTYPE           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RTYPEJ.GB  ",    "RTYPE           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RTYPE2J.GB ",    "RTYPE 2         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RTYPE2.GB  ",    "RTYPE 2         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RUBBLES2.GB",    "RUBBLE SAVER 2  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "RUBBLESA.GB",    "RUBBLESA        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ULTIMA.GB  ",    "RUNES OF VIRTUE ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "ULTIMA2.GB ",    "RUNES OF VIRTUE2",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "ROBOCVST.GB",    "RVT             ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BASKETSS.GB",    "S S BASKET BALL2",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FFL.GB     ",    "SAGA            ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "FFLJ.GB    ",    "SAGA            ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "FFL2J.GB   ",    "SAGA2           ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "FFL2.GB    ",    "SAGA2           ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "FFL3.GB    ",    "SAGA3           ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "FFL3J.GB   ",    "SAGA3           ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "SAGAIA.GB  ",    "SAGAIA          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SAMURAIS.GB",    "SAMURAI SHODOWN ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "SANGOKUS.GB",    "SANGOKUSHI      ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "SANRIOCA.GB",    "SANRIO CARNIVAL ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MONSTERW.GB",    "Saved game      ",    "N/A                 ",131.072),
                arrayOf(false, "SCOTLAND.GB",    "SCOTLANDYARD    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HIRYUNO.GB ",    "SD HIRYUNOKEN   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "LUPIN3RD.GB",    "SD LUPIN THE 3RD",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SDSEINTP.GB",    "SD SEINTPARADA01",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "SDGUNDAM.GB",    "SDGUNDAMKUNITORI",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SDSENGOK.GB",    "SDSENGOKUDEN2   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "SDSENGO3.GB",    "SDSENGOKUDEN3   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "VOLLEYBS.GB",    "SEASIDE VOLLEY  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MYSTICJJ.GB",    "SEIKEN DENSETSU ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "MYSTICJ.GB ",    "SEIKEN DENSETSU ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "SELECTIO.GB",    "SELECTION       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SENGOKUN.GB",    "SENGOKUNINJAKUN ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "SENSIBLE.GB",    "SENSIBLE SOCCER ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SERPENT.GB ",    "SERPENT         ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SHADOWWA.GB",    "SHADOW WARRIORS ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SHANGHAI.GB",    "SHANGHAI        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SHANGHAJ.GB",    "SHANGHAI        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SHIKINJY.GB",    "SHIKINJYO       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SHIPPODE.GB",    "SHIPPO DE BUN   ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SHISENSO.GB",    "SHISENSYO       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SHOOT.GB   ",    "SHOOT           ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SHOOT.GB   ",    "SHOOT           ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SHOUGI.GB  ",    "SHOUGI          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPORTSIK.GB",    "SI KIDS         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SIDE_POC.GB",    "SIDE POCKET     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SIMPSON.GB ",    "SIMPSON ESCAPE  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SIMPSON2.GB",    "SIMPSONS 2      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SIMPSON3.GB",    "SIMPSONS3       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SKATE_OR.GB",    "SKATE OR DIE BAD",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SMURF.GB   ",    "SMURFS          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SNEAKY_S.GB",    "SNEAKY SNAKES   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SNOOPYJ.GB ",    "SNOOPY          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SNOOPY.GB  ",    "SNOOPY          ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SNOWBRO.GB ",    "SNOW BROS.JR    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SOCCER.GB  ",    "SOCCER          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SOCCERBO.GB",    "SOCCER BOY      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SOCCERMA.GB",    "SOCCER MANIA    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SOLARSTR.GB",    "SOLARSTRIKER    ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SOLDAM.GB  ",    "SOLDAM GB       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SOLI_FUN.GB",    "SOLITAIRE FUNPAK",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SOLOMON.GB ",    "SOLOMON'S CLUB  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SOLOMONS.GB",    "SOLOMON'S CLUB  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SOUKOBA.GB ",    "SOUKOBAN        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SOUKOBA2.GB",    "SOUKOBAN2       ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SPACEINV.GB",    "SPACE INVADERS  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SPACEIN2.GB",    "SPACE INVADERS  ",    "ROM+MBC1            ", 52.288),
                arrayOf(false, "SPANKYS.GB ",    "SPANKY'S QUEST  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "KUNGFU.GB  ",    "SPARTAN X       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SPARTANX.GB",    "SPARTAN X       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SPEEDBA2.GB",    "SPEED BALL 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPEEDYJ.GB ",    "SPEEDY GONZALES ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SPEEDY.GB  ",    "SPEEDY GONZALES ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SPELLCHK.GB",    "SPELL CHECKER   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPIDERMA.GB",    "SPIDER-MAN      ",    "ROM+MBC1            ",65.536 ),
                arrayOf(false, "SPIDERM2.GB",    "SPIDER-MAN 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPIDERM3.GB",    "SPIDER-MAN 3 DMG",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPIDERMX.GB",    "SPIDERMAN XMEN  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPIROU.GB  ",    "SPIROU          ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SPOTJ.GB   ",    "SPOT            ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SPOT.GB    ",    "SPOT            ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "SPOTCOOL.GB",    "SPOT COOL ADV   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SPUDSADV.GB",    "SPUDS ADVENTURE ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SEAQUEST.GB",    "SQ DSV DMG      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SQUARE_D.GB",    "SQUARE DEAL     ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "STARWARR.GB",    "SRJ DMG         ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "STARSAVE.GB",    "STAR SAVER      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "KIRBYSS.GB ",    "STAR STACKER    ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "STARTNG.GB ",    "STAR TREK       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "STARTREK.GB",    "STAR TREK       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "STARWARS.GB",    "STAR WARS       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "STARGATE.GB",    "STARGATE        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "STREETF2.GB",    "STREET FIGHTER 2",    "ROM+MBC1            ",524.288),
                arrayOf(false, "SUMOFIGH.GB",    "SUMO FIGHTER    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUMOUFIG.GB",    "SUMOU FIGHTER   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "BEEDAMAN.GB",    "SUPER B DAMAN   ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "BLUESBRO.GB",    "SUPER BLUES     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERBL.GB ",    "SUPER BOMBLISS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERCH2.GB",    "SUPER CHINESE 2 ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "SUPERHUN.GB",    "SUPER HUNCHBACK ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERHUJ.GB",    "SUPER HUNCHBACK ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERKIC.GB",    "SUPER KICK OFF  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GBMARIO.GB ",    "SUPER MARIOLAND ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SUPERMV0.GB",    "SUPER MARIOLAND ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "GBMARIO.GB ",    "SUPER MARIOLAND ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SUPERMV1.GB",    "SUPER MARIOLAND ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SUPEROFF.GB",    "SUPER OFF ROAD  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERRCP.GB",    "SUPER RC PRO-AM ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SUPERRW.GB ",    "SUPER ROBOT WAR ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "SUPERCHL.GB",    "SUPERCHINESELAND",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "SUPERML3.GB",    "SUPERMARIOLAND3 ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "SUPERRW2.GB",    "SUPERROBOTWAR 2G",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "WWFSS2J.GB ",    "SUPERWWF        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WWFSS2.GB  ",    "SUPERWWF        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SWAMP.GB   ",    "SWAMP THING     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "RENJU.GB   ",    "TAIKYOKU RENJU  ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "TAILGATO.GB",    "TAIL GATOR      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "TALESPIN.GB",    "TALE SPIN       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TARZAN.GB  ",    "TARZAN          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TASMANIA.GB",    "TASMANIA STORY  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "TASMANIS.GB",    "TASMANIA STORY  ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "TAZMANIA.GB",    "TAZ-MANIA       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TECMO_BO.GB",    "TECMO BOWL      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TEKKYUFI.GB",    "TEKKYUFIGHT!    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TENCHI.GB  ",    "TENCHIWOKURAU   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "TENJINK2.GB",    "TENJIN KAISEN 2 ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TENJINK.GB ",    "TENJINKAISEN    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TENNIS.GB  ",    "TENNIS          ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "TENSAIBA.GB",    "TENSAIBAKABON   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TERMIN2.GB ",    "TERMINATOR 2    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TERMIN2T.GB",    "TERMINATOR 2 TAG",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TESSERAE.GB",    "TESSERAE        ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "TETRIS.GB  ",    "TETRIS          ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "TATTACK.GB ",    "TETRIS ATTACK   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "TBLAST.GB  ",    "TETRIS BLAST    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TETRISF.GB ",    "TETRIS FLASH    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TETRISP.GB ",    "TETRIS PLUS     ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "TETRIS2.GB ",    "TETRIS2         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "CHESSM.GB  ",    "THE CHESSMASTER ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "FIDGETTS.GB",    "THE FIDGETTS    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GBFIDGET.GB",    "THE FIDGETTS    ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "FLASH.GB   ",    "THE FLASH       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FLINT.GB   ",    "THE FLINTSTONES ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GETAWAY1.GB",    "THE GETAWAY     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "GETAWAY.GB ",    "THE GETAWAY     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "HUMANS.GB  ",    "THE HUMANS      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "JETSONS.GB ",    "THE JETSONS     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "LIONKING.GB",    "THE LION KING   ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "PAGEMAST.GB",    "THE PAGEMASTER  ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "PUNISHER.GB",    "THE PUNISHER    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SWORD.GB   ",    "THE SWORD OFHOPE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "SWORDG.GB  ",    "THE SWORD OFHOPE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "HARMONY.GB ",    "THEGAMEOFHARMONY",    "ROM Only            ", 32.768 ),
                arrayOf(false, "THUNDERB.GB",    "THUNDERBIRDS    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TINTIN.GB  ",    "TINTIN AU TIBET ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TINYTOO2.GB",    "TINY TOON 2     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TINYTOO3.GB",    "TINY TOON 3     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TINYTOOJ.GB",    "TINY TOON ADVENT",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TINYTOON.GB",    "TINY TOON ADVENT",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TINYWACK.GB",    "TINY TOON WACKY ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TITUSFOX.GB",    "TITUS THE FOX   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TMHT2.GB   ",    "TMHT BACK FROM S",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TMNT.GB    ",    "TMNT            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TMNT2.GB   ",    "TMNT 2          ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TMNTBF.GB  ",    "TMNT BACK FROM S",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TMNTFC.GB  ",    "TMNT FOOT CLAN  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TMNT3J.GB  ",    "TMNT3           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TMNT3.GB   ",    "TMNT3           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOM&JER2.GB",    "TOM AND JERRY   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOM&J.GB   ",    "TOM AND JERRY   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOM&JFA.GB ",    "TOM AND JERRY   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOPGUN2.GB ",    "TOPGUN 2        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TENNISTR.GB",    "TOPRANKTENNIS   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "TORPEDOR.GB",    "TORPEDO RANGE   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "TOTALCAR.GB",    "TOTAL CARNAGE   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOTSUGEK.GB",    "TOTSUGEKI TANK  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOUR_DE.GB ",    "TOUR DE THRASH  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOXICCRU.GB",    "TOXIC CRUSADERS ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TOYSTORE.GB",    "TOY STORY       ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "TRACKME.GB ",    "TRACK MEET      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRACKMEE.GB",    "TRACK MEET      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRACKMEA.GB",    "TRACK MEET HIRO ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRACK&FI.GB",    "TRACK&FIELD     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRAPPERS.GB",    "TRAPPERS TENGOKU",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRAX.GB    ",    "TRAX            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRIPWORL.GB",    "TRIP WORLD      ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "C_ROCK.GB  ",    "TRSI RULEZ      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TRUELIES.GB",    "TRUE LIES       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TSUMEGO1.GB",    "TSUMEGO 01      ",    "ROM+MBC1            ",  6.536 ),
                arrayOf(false, "TUBASAVS.GB",    "TUBASA VS       ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "TUMBLE~1.GB",    "TUMBLE POP      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TUMBLPOP.GB",    "TUMBLE POP      ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TURNANDB.GB",    "TURN AND BURN   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TURRICAN.GB",    "TURRICAN        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TWIN.GB    ",    "TWIN            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "TWINBEE.GB ",    "TWIN-BEE DA!!   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "GOLFU.GB   ",    "ULTRA GOLF      ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "ULTRAMAN.GB",    "ULTRAMAN        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ULTRAMAB.GB",    "ULTRAMAN BALL   ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ULTRAMNG.GB",    "ULTRAMAN GEKIDEN",    "ROM+MBC1            ",262.144),
                arrayOf(false, "UNDERCOV.GB",    "UNDER COVER COPS",    "ROM+MBC1            ",262.144),
                arrayOf(false, "UNIVERSA.GB",    "UNIVERSALSOLDIER",    "ROM+MBC1            ",262.144),
                arrayOf(false, "UNO2-SW.GB ",    "UNO2SMALL WORLD ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "FISHDUDJ.GB",    "UOOZU           ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "URUSEIYA.GB",    "URUSEIYATSURA   ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "VALATION.GB",    "VALATIONS       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "VATTLE_G.GB",    "VATTLE GIUCE    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "VEEDIOTS.GB",    "VEEDIOTS        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "VEGAS.GB   ",    "VEGAS STAKES    ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "VEGAS.GB   ",    "VEGAS STAKES    ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "VELIOUS2.GB",    "VELIOUS 2       ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "VSHERO.GB  ",    "VERSUS HERO     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "VIRTUALW.GB",    "VIRTUAL WARS    ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "VITAMINA.GB",    "VITAMINA KINGDOM",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "VOLLEY_F.GB",    "VOLLEY FIRE     ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "VSBATTLE.GB",    "VS BATTLER      ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "WORLDCIR.GB",    "W CIRCUIT SERIES",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WARIOBLA.GB",    "WARIO BLAST     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "WARRIOR.GB ",    "WARRIOR         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "WATER_WO.GB",    "WATER WORLD     ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "WAVERACE.GB",    "WAVERACE        ",    "ROM+MBC2+BATTERY    ",131.072),
                arrayOf(false, "WAYNEWLD.GB",    "WAYNE'S WORLD   ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "WEREBACK.GB",    "WEREBACK BC     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WORLDH2.GB ",    "WH2JET          ",    "ROM+MBC1            ",524.288),
                arrayOf(false, "WHEEL_OF.GB",    "WHEEL OF FORTUNE",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WILDSNAK.GB",    "WILDSNAKE       ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "WINNINGG.GB",    "WINNING GOAL    ",    "ROM+MBC1+RAM+BATTERY",131.072),
                arrayOf(false, "WINTER_G.GB",    "WINTER GOLD     ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WINTER_O.GB",    "WINTER OLYMPICS ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WIZARDRY.GB",    "WIZARDRY SOQ    ",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "WIZWARF.GB ",    "WIZARDS WARRIORS",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "WORDTRIS.GB",    "WORDTRIS        ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WORDZAP.GB ",    "WORDZAP         ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "WORLDB.GB  ",    "WORLD BOWLING   ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "WORLDBJ.GB ",    "WORLD BOWLING   ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "WORLDCUP.GB",    "WORLD CUP       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WORLDC1.GB ",    "WORLD CUP       ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WLDCUP94.GB",    "WORLD CUP USA 94",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "WORLDCUU.GB",    "WORLD CUP USA 94",    "ROM+MBC1+RAM+BATTERY",262.144),
                arrayOf(false, "WORLDICE.GB",    "WORLD ICE HOKKEY",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WORMS.GB   ",    "WORMS           ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "WWFRAW.GB  ",    "WWF RAW         ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "WWFSSJ.GB  ",    "WWF SUPERSTARS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WWFSS.GB   ",    "WWF SUPERSTARS  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WWFKORJ.GB ",    "WWFKOR          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "WWFKOR.GB  ",    "WWFKOR          ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "XEKKUSU.GB ",    "X               ",    "ROM+MBC2+BATTERY    ",262.144),
                arrayOf(false, "XENON2J.GB ",    "XENON 2         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "XENON2.GB  ",    "XENON 2         ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "XERD2.GB   ",    "XERD!!          ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "YAIBA.GB   ",    "YAIBA           ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "YAKUMAN.GB ",    "YAKUMAN         ",    "ROM Only            ", 32.768 ),
                arrayOf(false, "YAMATO.GB  ",    "YAMATO          ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "YOGIBEAR.GB",    "YOGIS GOLDRUSH  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "Y_COOKIE.GB",    "YOSHI'S COOKIE  ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "YOSHI.GB   ",    "YOSSY NO TAMAGO ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "MARIO&YJ.GB",    "YOSSY NO TAMAGO ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "YUUYUU1.GB ",    "YUUYUU-1        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "YUUYUU2.GB ",    "YUUYUU-2        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "YUUYUU3.GB ",    "YUUYUU-3        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "YUUYUU4.GB ",    "YUUYUU-4        ",    "ROM+MBC1            ",262.144),
                arrayOf(false, "ZELDAF.GB  ",    "ZELDA           ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "ZELDAJ.GB  ",    "ZELDA           ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "ZELDA0.GB  ",    "ZELDA           ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "ZELDA1.GB  ",    "ZELDA           ",    "ROM+MBC1+RAM+BATTERY",524.288),
                arrayOf(false, "ZEN.GB     ",    "ZEN             ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ZEOTH.GB   ",    "ZEOTH           ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ZOIDS.GB   ",    "ZOIDS J1        ",    "ROM+MBC1            ", 65.536 ),
                arrayOf(false, "ZOOL.GB    ",    "ZOOL            ",    "ROM+MBC1            ",131.072),
                arrayOf(false, "ZOOP.GB    ",    "ZOOP            ",    "ROM+MBC1            ", 65.536)
        )
    }
}

